baseURL = "https://vittoriananna.github.io/"
languageCode = "en-uk"
title = "Vittoria Nanna"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  googleSiteVerification = "HxdTBZVg3aHIrg5bkHGwHas8aTpw8nlvT6aYpjrksB4"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/posts/whoiam/"
  weight = 10

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 20