baseURL = "https://vittoriananna.github.io/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
title = "Vittoria Nanna"
theme = "PaperMod"
enableRobotsTXT = true

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-uk"
    title = "Vittoria Nanna"
    weight = 1

  [languages.it]
    languageName = "Italiano"
    languageCode = "it-it"
    title = "Vittoria Nanna"
    weight = 2


[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  googleSiteVerification = "HxdTBZVg3aHIrg5bkHGwHas8aTpw8nlvT6aYpjrksB4"
  [params.homeInfoParams]
    Title = "Hello there, I am Vittoria 👋"
    Content = "I write scattered notes on science and life, when I'm not out running."
    imageUrl = "/img/avatar.jpg"
    imageWidth = 120
    imageHeight = 120

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/vittoriananna"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/vittoria-nanna/"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/posts/whoiam/"
  weight = 10

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts/"
  weight = 20