baseURL = "https://vittoriananna.github.io/"
languageCode = "en-uk"
title = "Vittoria Nanna"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  googleSiteVerification = "HxdTBZVg3aHIrg5bkHGwHas8aTpw8nlvT6aYpjrksB4"